# Generated by Django 3.2.18 on 2023-08-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0022_auto_20230805_1457'),
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
    ]
