# Generated by Django 3.2.18 on 2023-08-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20230808_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='company',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='company',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='company_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='patent_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='personal_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
