# Generated by Django 3.2.18 on 2023-08-08 17:42
from cdata.models import Contact
from follow.models import SocialMedia

from django.db import migrations
def migrate_social_media_links(apps, schema_editor):

    for contact in Contact.objects.all():
        SocialMedia.objects.create(
            contact=contact,
            twitter_url=contact.twitter_url,
            linkedin_url=contact.linkedin_url,
            personal_url=contact.personal_url_ref,
            company_url=contact.company_url_ref,
            patent_url=contact.patent_url_ref,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20230808_1741'),
    ]

    operations = [
        migrations.RunPython(migrate_social_media_links),
    ]
