# Generated by Django 3.2.18 on 2023-08-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0004_auto_20230808_1742'),
    ]

    operations = [
    ]
