# Generated by Django 3.2.18 on 2023-08-08 17:52

from cdata.models import Contact
from follow.models import SocialMedia

from django.db import migrations

def migrate_social_media_links(apps, schema_editor):
    # Fetch the current state of the models during this migration.
    Contact = apps.get_model('cdata', 'Contact')
    Company = apps.get_model('cdata', 'Company')
    SocialMedia = apps.get_model('follow', 'SocialMedia')

    # Loop through all Contact instances.
    for contact in Contact.objects.all():
        # Check if any social media link exists for the contact.
        if contact.twitter_url or contact.linkedin_url or contact.company_url_ref or contact.patent_url_ref or contact.personal_url_ref:  # ... or any other fields you have
            # Create or update a single SocialMedia instance for this contact.
            social_media, created = SocialMedia.objects.get_or_create(contact=contact)

            # Set company reference from the contact's associated company.
            #social_media.company = contact.company

            # Update the social media link fields.
            if contact.twitter_url:
                social_media.twitter_url = contact.twitter_url
            if contact.linkedin_url:
                social_media.linkedin_url = contact.linkedin_url
            if contact.company_url_ref:
                social_media.company_url = contact.company_url_ref
            if contact.patent_url_ref:
                social_media.patent_url = contact.patent_url_ref
            if contact.personal_url_ref:
                social_media.personal_url = contact.personal_url_ref
            # ... repeat for other platforms as needed

            # Save the updated or new SocialMedia instance.
            social_media.save()



class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20230808_1741'),
    ]

    operations = [
        migrations.RunPython(migrate_social_media_links),
    ]