# Generated by Django 3.2.18 on 2023-08-08 17:52

from cdata.models import Contact
from follow.models import SocialMedia
from cdata.models import Contact

from django.db import migrations

def copy_social_media_links(apps, schema_editor):
    # Fetch the current state of the models during this migration.
    Contact = apps.get_model('cdata', 'Contact')
    Company = apps.get_model('cdata', 'Company')
    SocialMedia = apps.get_model('follow', 'SocialMedia')

    # Loop through all Contact instances.
    for social_media in SocialMedia.objects.all():
        # Check if any social media link exists for the contact.


            # Set company reference from the contact's associated company.
            #social_media.company = contact.company

            # Update the social media link fields.
        social_media.twitter_url = social_media.contact.twitter_url
        social_media.linkedin_url = social_media.contact.linkedin_url
        social_media.company_url = social_media.contact.company_url_ref
        social_media.patent_url = social_media.contact.patent_url_ref
        social_media.personal_url = social_media.contact.personal_url_ref
        social_media.save()





class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0005_auto_20230808_1752'),
    ]

    operations = [
        migrations.RunPython(copy_social_media_links),
    ]
