# Generated by Django 3.2.18 on 2023-08-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0006_auto_20230809_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='company',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='company',
        ),
    ]
