# Generated by Django 3.2.18 on 2023-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cdata', '0025_auto_20231006_1559'), ('cdata', '0026_auto_20231007_0021')]

    dependencies = [
        ('cdata', '0024_edasuppliertool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edasuppliertools',
            name='id',
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='edasuppliertools',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
