# Generated by Django 3.2.18 on 2023-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0025_auto_20231006_1559'),
    ]

    operations = [

        migrations.AddField(
            model_name='edasuppliertools',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='name',
            field=models.CharField(max_length=200),
        ),

    ]
