# Generated by Django 3.2.18 on 2023-07-30 21:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0003_auto_20230718_1401'),
        ('cdata', '0021_auto_20230729_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroupEDASupplierTools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(choices=[(Decimal('0.0'), '0.0'), (Decimal('0.1'), '0.1'), (Decimal('0.2'), '0.2'), (Decimal('0.3'), '0.3'), (Decimal('0.4'), '0.4'), (Decimal('0.5'), '0.5'), (Decimal('0.6'), '0.6'), (Decimal('0.7'), '0.7'), (Decimal('0.8'), '0.8'), (Decimal('0.9'), '0.9'), (Decimal('1.0'), '1.0')], decimal_places=1, default=0.5, max_digits=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('secondary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.company')),
                ('company_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.companygroup')),
                ('company_group_hier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hierarchy.companygrouphierarchy')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.edasuppliertools')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroupEDADesignFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(choices=[(Decimal('0.0'), '0.0'), (Decimal('0.1'), '0.1'), (Decimal('0.2'), '0.2'), (Decimal('0.3'), '0.3'), (Decimal('0.4'), '0.4'), (Decimal('0.5'), '0.5'), (Decimal('0.6'), '0.6'), (Decimal('0.7'), '0.7'), (Decimal('0.8'), '0.8'), (Decimal('0.9'), '0.9'), (Decimal('1.0'), '1.0')], decimal_places=1, default=0.5, max_digits=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.company')),
                ('company_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.companygroup')),
                ('company_group_hier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hierarchy.companygrouphierarchy')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.edadesignflow')),
            ],
        ),
    ]
