# Generated by Django 3.2.18 on 2023-09-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygroupedadesignflow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companygroupedadesignflow',
            name='company_group_hier',
        ),
        migrations.RemoveField(
            model_name='companygroupedasuppliertools',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companygroupedasuppliertools',
            name='company_group_hier',
        ),
    ]
