# Generated by Django 3.2.18 on 2023-10-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_flow', '0003_auto_20230925_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyGroupEDADesignFlow',
        ),
    ]
