# Generated by Django 3.2.18 on 2023-10-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_flow', '0004_delete_companygroupedadesignflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygroupedasuppliertools',
            name='name',
        ),
    ]
