# Generated by Django 3.2.18 on 2023-10-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0028_auto_20231007_2247'),
        ('design_flow', '0005_remove_companygroupedasuppliertools_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygroupedasuppliertools',
            name='name',
            field=models.ForeignKey(default='VCS', on_delete=django.db.models.deletion.PROTECT, to='cdata.edasuppliertools'),
            preserve_default=False,
        ),
    ]
