# Generated by Django 3.2.18 on 2023-06-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0003_city_companyoffice_contact_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
