# Generated by Django 3.2.18 on 2023-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0005_auto_20230613_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
