# Generated by Django 3.2.18 on 2023-06-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0006_company_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoffice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.city'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.country'),
        ),
    ]
