# Generated by Django 3.2.18 on 2023-06-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0007_auto_20230616_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyoffice',
            old_name='streeet_address2',
            new_name='street_address2',
        ),
    ]
