# Generated by Django 3.2.18 on 2023-06-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0008_rename_streeet_address2_companyoffice_street_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoffice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdata.city'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdata.country'),
        ),
    ]
