# Generated by Django 3.2.18 on 2023-06-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0009_auto_20230617_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='country',
        ),
    ]
