# Generated by Django 3.2.18 on 2023-06-28 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0010_rename_country_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDADesignFlowSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eda_design_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.edadesignflow')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.companyoffice'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='Jane', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ticker_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.country'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.city'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.country'),
        ),
        migrations.AlterField(
            model_name='companysupplierspend',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
        migrations.AlterField(
            model_name='companysupplierspend',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdata.supplier'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
        migrations.CreateModel(
            name='EDASupplierTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_website', models.URLField()),
                ('meta_data', models.TextField()),
                ('description', models.TextField()),
                ('competitive_positioning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eda_design_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.edadesignflow')),
                ('eda_design_flow_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.edadesignflowsubcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eda_design_flows', models.ManyToManyField(blank=True, to='cdata.EDADesignFlow')),
                ('eda_tools_primary', models.ManyToManyField(blank=True, related_name='eda_tools_primary', to='cdata.EDASupplierTools')),
                ('eda_tools_secondary', models.ManyToManyField(blank=True, related_name='eda_tools_secondary', to='cdata.EDASupplierTools')),
                ('eda_tools_tertiary', models.ManyToManyField(blank=True, related_name='eda_tools_tertiary', to='cdata.EDASupplierTools')),
            ],
        ),
    ]
