# Generated by Django 3.2.18 on 2023-07-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0011_auto_20230628_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.country'),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.company'),
        ),
        migrations.AlterField(
            model_name='companysupplierspend',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.company'),
        ),
        migrations.AlterField(
            model_name='edadesignflowsubcategory',
            name='eda_design_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.edadesignflow'),
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='eda_design_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.edadesignflow'),
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='eda_design_flow_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.edadesignflowsubcategory'),
        ),
    ]
