# Generated by Django 3.2.18 on 2023-07-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0012_auto_20230701_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
