# Generated by Django 3.2.18 on 2023-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0013_contact_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
