# Generated by Django 3.2.18 on 2023-07-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0014_alter_contact_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
