# Generated by Django 3.2.18 on 2023-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0016_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_url_ref',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
