# Generated by Django 3.2.18 on 2023-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0017_auto_20230713_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edasuppliertools',
            name='competitive_positioning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='meta_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='product_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
