# Generated by Django 3.2.18 on 2023-07-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0018_auto_20230721_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.company'),
        ),
    ]
