# Generated by Django 3.2.18 on 2023-07-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0019_companygroup_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.companygroup'),
        ),
    ]
