# Generated by Django 3.2.18 on 2023-07-29 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0020_contact_company_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygroup',
            name='eda_design_flows',
        ),
        migrations.RemoveField(
            model_name='companygroup',
            name='eda_tools_primary',
        ),
        migrations.RemoveField(
            model_name='companygroup',
            name='eda_tools_secondary',
        ),
        migrations.RemoveField(
            model_name='companygroup',
            name='eda_tools_tertiary',
        ),
        migrations.AddField(
            model_name='companygroup',
            name='group_headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdata.companyoffice'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='product_url_ref',
            field=models.URLField(blank=True, null=True),
        ),
    ]
