# Generated by Django 3.2.18 on 2023-08-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0021_auto_20230729_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='patent_url_ref',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='personal_url_ref',
            field=models.URLField(blank=True, null=True),
        ),
    ]
