# Generated by Django 3.2.18 on 2023-08-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0022_auto_20230805_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company_url_ref',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='patent_url_ref',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='personal_url_ref',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter_url',
        ),
    ]
