# Generated by Django 3.2.18 on 2023-09-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0023_auto_20230829_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDASupplierTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('product_website', models.URLField(blank=True, null=True)),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('competitive_positioning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eda_design_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.edadesignflow')),
                ('eda_design_flow_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdata.edadesignflowsubcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdata.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
