# Generated by Django 3.2.18 on 2023-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0026_auto_20231007_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edadesignflowsubcategory',
            name='name',
            field=models.CharField(default='Spectre III', max_length=100),
        ),
    ]
