# Generated by Django 3.2.18 on 2023-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdata', '0027_alter_edadesignflowsubcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edasuppliertools',
            name='id',
        ),
        migrations.AlterField(
            model_name='edasuppliertools',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
